### ISSUE TITLE
add LICENSE?

### ISSUE THREAD

**Issue by swyxio** [AnnieTaylorCHEN/meowflix#1]
hey Annie! loved your talk!

just wanted to suggest adding a license. this can help people forking or reading the code. if i wanted to show this demo for a talk I would need to check the license, for example.

github makes it easy to add licenses: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by AnnieTaylorCHEN** [comment]
Thanks, I've done that now. :smile_cat:
